### PR TITLE
fix up controllers and models and denormalize avg rating

### PR DESCRIPTION
**Pull request by DireCorgi**
- Fixed N+1 queries
- Denormalized Avg Rating for cocktails
- Cleaned up some code
- Moved some logic from controllers to model

### CODE REVIEW

**Comment by diiiefiend** [comment]
LGTM but want to test on my local before merging

**Comment by diiiefiend** [comment]
@DireCorgi : pulled and it looks like everything works. however i did notice this in the rails server log when updating a rating:
```
Started PUT "/api/cocktails/40/ratings/113" for ::1 at 2017-05-26 19:03:28 -0400
Processing by Api::RatingsController#update as JSON
  Parameters: {"rating"=>{"id"=>113, "rating"=>4, "user_id"=>3, "body"=>"testing", "scale_composition"=>nil, "scale_spirited"=>nil, "time"=>"June 26th, 2016 17:25", "username"=>"guest", "cocktail_id"=>40, "created_at"=>"2016-06-26T17:25:32.641-04:00", "updated_at"=>"2016-06-26T17:25:32.641-04:00", "rating_num"=>2}, "id"=>"113"}
  Rating Load (0.3ms)  SELECT  "ratings".* FROM "ratings" WHERE "ratings"."id" = $1 LIMIT 1  [["id", 113]]
Unpermitted parameters: id, rating, user_id, scale_composition, scale_spirited, time, username, created_at, updated_at
Unpermitted parameters: id, rating, user_id, scale_composition, scale_spirited, time, username, created_at, updated_at
   (0.2ms)  BEGIN
  SQL (0.4ms)  UPDATE "ratings" SET "rating" = $1, "updated_at" = $2 WHERE "ratings"."id" = $3  [["rating", 2], ["updated_at", "2017-05-26 19:03:28.682895"], ["id", 113]]
  Cocktail Load (0.4ms)  SELECT  "cocktails".* FROM "cocktails" WHERE "cocktails"."id" = $1 LIMIT 1  [["id", 40]]
```

do you know what could be causing the 'unpermitted parameters' output?

**Comment by DireCorgi** [comment]
This was always broken. I added the scales to the permitted params. You will still get this warning because you using the dumb clean params thing.

**Comment by DireCorgi** [comment]
NVM this is actually just a warning message and its working as intended.

**Review by diiiefiend — APPROVED** [review]
wowee 💯

**Pull request merged**
